export const GET_QUESTIONS_REQUEST = 'GET_QUESTIONS_REQUEST';
export const GET_QUESTIONS_RESULT = 'GET_QUESTIONS_RESULT';
export const GET_QUESTIONS_FAIL = 'GET_QUESTIONS_FAIL';

export const POST_QUESTION_ANSWER = 'POST_QUESTION_ANSWER';
export const GET_NEXT_QUESTION = 'GET_NEXT_QUESTION';
export const RESTART_QUIZ = 'RESTART_QUIZ';